/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI */

#ifndef _Included_JNI
#define _Included_JNI
#ifdef __cplusplus
#include <iostream>
extern "C" {
#endif

JNIEXPORT void JNICALL Java_net_robot_wavem_jni_Jni_say_1hello(JNIEnv* env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif