/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI */

#ifndef _Included_JNI
#define _Included_JNI
#ifdef __cplusplus
#include <cstdlib>
#include <string>
#include "rclcpp/rclcpp.hpp"
#include "geometry_msgs/msg/twist.hpp"
#define DEFAULT_ARGC 0
#define DEFAULT_ARGV nullptr 
#define DEFAULT_NODE_NAME "rcljava"
#define SUB_PUBLSIHER_NODE_NAME "cmd_vel_publisher"
#define SUB_SUBSCRIPTION_NODE_NAME "cmd_vel_subscription"
#define DEFAULT_TOPIC_NAME "/cmd_vel"
#define DEFAULT_QOS 10
#define DEFAULT_CALLBACK_NAME "cmdVelSubscriptionCallback"
extern "C" {
#endif

JNIEXPORT void JNICALL Java_net_robot_wavem_publisher_cmd_1vel_CmdVelPublisher_publish_1to_1cmd_1vel(JNIEnv * j_env, jobject j_obj);
JNIEXPORT void JNICALL Java_net_robot_wavem_subscription_cmd_1vel_CmdVelSubscription_subscribe_1from_1cmd_1vel(JNIEnv * j_env, jobject j_obj);

#ifdef __cplusplus
}
#endif
#endif