/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI */

#ifndef _Included_JNI
#define _Included_JNI
#ifdef __cplusplus
#include "common/rcljava_common_connections.hpp"
extern "C" {
#endif

JNIEXPORT void JNICALL Java_net_robot_wavem_publisher_cmd_1vel_CmdVelPublisher_publish_1to_1cmd_1vel(JNIEnv * j_env, jobject j_obj, jobject j_twist_hash_map);
JNIEXPORT void JNICALL Java_net_robot_wavem_subscription_cmd_1vel_CmdVelSubscription_subscribe_1from_1cmd_1vel(JNIEnv * j_env, jobject j_obj);

#ifdef __cplusplus
}
#endif
#endif