/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI */

#ifndef _Included_JNI
#define _Included_JNI
#ifdef __cplusplus
#include "common/rcljava_common_connections.hpp"
extern "C" {
#endif

JNIEXPORT void JNICALL Java_net_robot_wavem_subscription_odometry_OdometrySubscription_subscribe_1from_1odom(JNIEnv * j_env, jobject j_obj);

#ifdef __cplusplus
}
#endif
#endif