/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI */

#ifndef _Included_JNI
#define _Included_JNI
#ifdef __cplusplus
#include <cstdlib>
#include <string>
#include "rclcpp/rclcpp.hpp"
#include "std_msgs/msg/string.hpp"
#define DEFAULT_ARGC 0
#define DEFAULT_ARGV nullptr 
#define DEFAULT_NODE_NAME "rcljava"
#define SUB_PUBLSIHER_NODE_NAME "chatter_publisher"
#define SUB_SUBSCRIPTION_NODE_NAME "chatter_subscription"
#define DEFAULT_TOPIC_NAME "/chatter"
#define DEFAULT_QOS 10
#define DEFAULT_CALLBACK_NAME "chatterSubscriptionCallback"
extern "C" {
#endif

JNIEXPORT void JNICALL Java_net_robot_wavem_publisher_chatter_ChatterPublisher_publish_1to_1chatter(JNIEnv * j_env, jobject j_obj, jobjectArray j_chatter_message_array);
JNIEXPORT void JNICALL Java_net_robot_wavem_subscription_chatter_ChatterSubscription_subscribe_1from_1chatter(JNIEnv * j_env, jobject j_obj);

#ifdef __cplusplus
}
#endif
#endif